Add/remove wanted skills, personalities, horoscope, leaders; save/load; calculate numPrettyGirls
vivtony00/teamform-seed pull request #17
Opened 2016-11-12 09:19 UTC by hmhv1222

- Added functions of add/remove wanted skills, personalities, horoscope, team leaders, and change team leaders

- Added function of calculating number of pretty girls

- Modified save/load function

2016-11-12 12:53 UTC, vivtony00 commented
please pull the master 
and 
send the pull request again.

2016-11-12 18:23 UTC, vivtony00 commented on app/js/team.js
> +	refPath = "events/" + eventName + "/admin";
如果轉event既path既話就全世界都要轉(eg.做緊admin.js既人)
下次可以講聲

2016-11-12 18:26 UTC, vivtony00 commented on app/js/team.js
> +app.controller("MyAuthCtrl", ["$scope", "$firebaseAuth",
呢個唔係真係俾你copy&paste...
係inject個$firebaseAuth落個controller到...
13呢行改做
`.controller('TeamCtrl', ['$scope', '$firebaseObject', '$firebaseArray', "$firebaseAuth"`

2016-11-12 18:26 UTC, vivtony00 commented on app/js/team.js
> +  function($scope, $firebaseAuth)
呢行改做
function($scope, $firebaseObject, $firebaseArray, $firebaseAuth)

2016-11-12 18:27 UTC, vivtony00 requested changes
see the comment inside the code

2016-11-13 07:12 UTC, hmhv1222 commented on app/js/team.js
> +app.controller("MyAuthCtrl", ["$scope", "$firebaseAuth",
ok this was done by wasin

2016-11-13 07:16 UTC, hmhv1222 commented on app/js/team.js
> +app.controller("MyAuthCtrl", ["$scope", "$firebaseAuth",
i didnt check

2016-11-13 07:32 UTC, hmhv1222 commented on app/js/team.js
> +	refPath = "events/" + eventName + "/admin";
ok wont change anymore

2016-11-13 07:46 UTC, hmhv1222 commented
Corrected Wasin’s controller injection mistake

2016-11-13 11:13 UTC, closed without merging